name: Atualizar Escala PGD

on:
  push:
    branches:
      - main
  # Executa a cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r utils/requirements.txt

    - name: Criar arquivo de credenciais
      run: echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > utils/service_account.json
      
    - name: Executar script para exportar CSV
      run: python utils/exportaCSV.py
      env:
        URL_CHAT: ${{ secrets.URL_CHAT }}

    - name: Fazer commit das alterações
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add utils/planilha_exportada.csv
        # Verifica se há alterações para commitar
        if git diff --staged --quiet; then
          echo "Nenhuma alteração para commitar."
        else
          git commit -m "Atualização automática da escala PGD"
          git push
        fi